Add fgnu89-inline flags to allow compiling legacy gcc stuff
/openwrt/backfire-10.03.2-orig/build_dir/toolchain-mips_gcc-4.3.3+cs_uClibc-0.9.30.1/gcc-4.3.3/gcc/cgraph.h:408:7: note: in
expansion of macro 'gcc_assert'
       gcc_assert (TREE_CODE (node->decl) == VAR_DECL);
       ^
/openwrt/backfire-10.03.2-orig/build_dir/toolchain-mips_gcc-4.3.3+cs_uClibc-0.9.30.1/gcc-4.3.3/gcc/gcov-io.h: In function
'gcov_position':
/openwrt/backfire-10.03.2-orig/build_dir/toolchain-mips_gcc-4.3.3+cs_uClibc-0.9.30.1/gcc-4.3.3/gcc/system.h:577:55: warning: ISO C
does not support '__FUNCTION__' predefined identifier [-Wpedantic]
    ((void)(!(EXPR) ? fancy_abort (__FILE__, __LINE__, __FUNCTION__), 0 : 0))
                                                       ^
/openwrt/backfire-10.03.2-orig/build_dir/toolchain-mips_gcc-4.3.3+cs_uClibc-0.9.30.1/gcc-4.3.3/gcc/gcov-io.h:588:3: note: in
expansion of macro 'gcc_assert'
   gcc_assert (gcov_var.mode > 0);
   ^
/openwrt/backfire-10.03.2-orig/build_dir/toolchain-mips_gcc-4.3.3+cs_uClibc-0.9.30.1/gcc-4.3.3/gcc/toplev.c: At top level:
/openwrt/backfire-10.03.2-orig/build_dir/toolchain-mips_gcc-4.3.3+cs_uClibc-0.9.30.1/gcc-4.3.3/gcc/toplev.c:545:1: error:
redefinition of 'floor_log2'
 floor_log2 (unsigned HOST_WIDE_INT x)
 ^
In file included from
/openwrt/backfire-10.03.2-orig/build_dir/toolchain-mips_gcc-4.3.3+cs_uClibc-0.9.30.1/gcc-4.3.3/gcc/toplev.c:58:0:
/openwrt/backfire-10.03.2-orig/build_dir/toolchain-mips_gcc-4.3.3+cs_uClibc-0.9.30.1/gcc-4.3.3/gcc/toplev.h:178:1: note: previous
definition of 'floor_log2' was here
 floor_log2 (unsigned HOST_WIDE_INT x)
 ^
/openwrt/backfire-10.03.2-orig/build_dir/toolchain-mips_gcc-4.3.3+cs_uClibc-0.9.30.1/gcc-4.3.3/gcc/toplev.c:580:1: error:
redefinition of 'exact_log2'
 exact_log2 (unsigned HOST_WIDE_INT x)
 ^
In file included from
/openwrt/backfire-10.03.2-orig/build_dir/toolchain-mips_gcc-4.3.3+cs_uClibc-0.9.30.1/gcc-4.3.3/gcc/toplev.c:58:0:
/openwrt/backfire-10.03.2-orig/build_dir/toolchain-mips_gcc-4.3.3+cs_uClibc-0.9.30.1/gcc-4.3.3/gcc/toplev.h:184:1: note: previous
definition of 'exact_log2' was here
 exact_log2 (unsigned HOST_WIDE_INT x)
 ^
In file included from
/openwrt/backfire-10.03.2-orig/build_dir/toolchain-mips_gcc-4.3.3+cs_uClibc-0.9.30.1/gcc-4.3.3/gcc/toplev.c:30:0:
/openwrt/backfire-10.03.2-orig/build_dir/toolchain-mips_gcc-4.3.3+cs_uClibc-0.9.30.1/gcc-4.3.3/gcc/toplev.c: In function
'push_srcloc':
/openwrt/backfire-10.03.2-orig/build_dir/toolchain-mips_gcc-4.3.3+cs_uClibc-0.9.30.1/gcc-4.3.3/gcc/system.h:577:55: warning: ISO C
does not support '__FUNCTION__' predefined identifier [-Wpedantic]
    ((void)(!(EXPR) ? fancy_abort (__FILE__, __LINE__, __FUNCTION__), 0 : 0))
                                                       ^
/openwrt/backfire-10.03.2-orig/build_dir/toolchain-mips_gcc-4.3.3+cs_uClibc-0.9.30.1/gcc-4.3.3/gcc/toplev.c:973:3: note: in
expansion of macro 'gcc_assert'
   gcc_assert (!input_file_stack_restored);
   ^
/openwrt/backfire-10.03.2-orig/build_dir/toolchain-mips_gcc-4.3.3+cs_uClibc-0.9.30.1/gcc-4.3.3/gcc/toplev.c: In function
'pop_srcloc':
/openwrt/backfire-10.03.2-orig/build_dir/toolchain-mips_gcc-4.3.3+cs_uClibc-0.9.30.1/gcc-4.3.3/gcc/system.h:577:55: warning: ISO C
does not support '__FUNCTION__' predefined identifier [-Wpedantic]
    ((void)(!(EXPR) ? fancy_abort (__FILE__, __LINE__, __FUNCTION__), 0 : 0))
                                                       ^
/openwrt/backfire-10.03.2-orig/build_dir/toolchain-mips_gcc-4.3.3+cs_uClibc-0.9.30.1/gcc-4.3.3/gcc/toplev.c:1000:3: note: in
expansion of macro 'gcc_assert'
   gcc_assert (!input_file_stack_restored);
   ^
Makefile:2394: recipe for target 'toplev.o' failed
make[5]: *** [toplev.o] Error 1
make[5]: Leaving directory
'/openwrt/backfire-10.03.2-orig/build_dir/toolchain-mips_gcc-4.3.3+cs_uClibc-0.9.30.1/gcc-4.3.3-minimal/gcc'
Makefile:4758: recipe for target 'all-gcc' failed
make[4]: *** [all-gcc] Error 2
make[4]: Leaving directory '/openwrt/backfire-10.03.2-orig/build_dir/toolchain-mips_gcc-4.3.3+cs_uClibc-0.9.30.1/gcc-4.3.3-minimal'
Makefile:303: recipe for target
'/openwrt/backfire-10.03.2-orig/build_dir/toolchain-mips_gcc-4.3.3+cs_uClibc-0.9.30.1/gcc-4.3.3/.prepared' failed
make[3]: *** [/openwrt/backfire-10.03.2-orig/build_dir/toolchain-mips_gcc-4.3.3+cs_uClibc-0.9.30.1/gcc-4.3.3/.prepared] Error 2
make[3]: Leaving directory '/openwrt/backfire-10.03.2-orig/toolchain/gcc'
toolchain/Makefile:70: recipe for target 'toolchain/gcc/prepare' failed
make[2]: *** [toolchain/gcc/prepare] Error